# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-18 19:37
import enumfields.fields
from django.db import migrations

import elisio.verse.VerseFactory


def load_initial_data(self, orm):
    from django.core.management import call_command
    call_command('loaddata', 'initial_data.xml')


class Migration(migrations.Migration):
    dependencies = [
        ('versescanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseverse',
            name='verseType',
            field=enumfields.fields.EnumField(default=1, enum=elisio.verse.VerseFactory.VerseType, max_length=10),
        ),
        migrations.AddField(
            model_name='poem',
            name='verseForm',
            field=enumfields.fields.EnumField(default=1, enum=elisio.verse.VerseFactory.VerseForm, max_length=10),
        ),
        migrations.RunPython(load_initial_data)
    ]
