# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-19 21:47
import django.db.models.deletion
import elisio.parser.versefactory
import enumfields.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('versescanner', '0005_auto_20170509_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing', models.DateTimeField(auto_now=True)),
                ('items_at_creation_time', models.IntegerField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BatchItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='batchrun',
            name='user',
        ),
        migrations.AlterField(
            model_name='batchrun',
            name='initiator',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='batchrunresult',
            name='structure',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='batchrunresult',
            name='zeleny',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.CreateModel(
            name='DatabaseBatchItem',
            fields=[
                ('batchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False,
                                                       to='versescanner.BatchItem')),
                ('object_type', models.CharField(max_length=10)),
                ('object_id', models.IntegerField(blank=True)),
                ('relation', models.CharField(max_length=10)),
                ('negation', models.BooleanField(default=False)),
            ],
            bases=('versescanner.batchitem',),
        ),
        migrations.CreateModel(
            name='InputBatchItem',
            fields=[
                ('batchitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE,
                                                       parent_link=True, primary_key=True, serialize=False,
                                                       to='versescanner.BatchItem')),
                ('contents', models.CharField(max_length=70)),
                ('scanned_as', enumfields.fields.EnumField(enum=elisio.parser.versefactory.VerseType, max_length=10,
                                                           null=True)),
            ],
            bases=('versescanner.batchitem',),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='versescanner.Batch'),
        ),
        migrations.AddField(
            model_name='batchitem',
            name='dependent_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='versescanner.BatchItem'),
        ),
        migrations.AddField(
            model_name='batchrun',
            name='batch',
            field=models.ForeignKey(null=True, default=None, on_delete=django.db.models.deletion.CASCADE,
                                    to='versescanner.Batch'),
        ),
    ]
