# Generated by Django 3.2 on 2021-04-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('versescanner', '0009_auto_20210401_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordoccurrence',
            name='word',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
